<presentation> = version slides
<version> = <"@ version 1\n">
<slides> = slide { <"\n"> slide }
slide = <"# slide\n"> { line <"\n"> }
<line> = vertical-space | centered-text | ( !centered-text | !vertical-space ) text
vertical-space = <":">
centered-text = <"|"> text
<text> = #"[^\n]*"
