<presentation> = { line }
<line> = inner-line <'\n'>
<inner-line> = control-line | !control-line content-line
control-line = <'# '> ( command | key-value-pair )
command = 'slide'
key-value-pair = key <': '> value
key = #'[a-zA-Z][a-zA-Z0-9-]*'
value = #'[^\n]+'
content-line = ( bullet | sub-bullet | (!bullet | !sub-bullet) free-text )
free-text = #'[^\n]*'
bullet = <'* '> free-text
sub-bullet = <' * '> free-text
